#pragma config(Motor,  motorA,          a,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          b,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          c,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
  motor[motorB]=100;
  motor[motorC]=100;
  wait1Msec(3700);
}


